name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build with Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v4
      with:
        buildozer_version: stable
        command: buildozer android debug
        repository_root: .

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AI_Watermark_Killer_APK
        path: bin/*.apk
